// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVUbpvQXrB8tqBw2hDvgdHJ5h00x6FPWk',
    appId: '1:178734014478:web:45080492e783f238455c5f',
    messagingSenderId: '178734014478',
    projectId: 'projetofinal-10227',
    authDomain: 'projetofinal-10227.firebaseapp.com',
    storageBucket: 'projetofinal-10227.appspot.com',
    measurementId: 'G-2F4EQPGW0T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz_EhOeB7DF_I0uoaFtNJ26YgDeA89JsU',
    appId: '1:178734014478:android:22c4686a333977c0455c5f',
    messagingSenderId: '178734014478',
    projectId: 'projetofinal-10227',
    storageBucket: 'projetofinal-10227.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCuNJv3BS3Qs2H1hOG2pJTiQOILSyUCdo',
    appId: '1:178734014478:ios:1edfc4a9149a1033455c5f',
    messagingSenderId: '178734014478',
    projectId: 'projetofinal-10227',
    storageBucket: 'projetofinal-10227.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCuNJv3BS3Qs2H1hOG2pJTiQOILSyUCdo',
    appId: '1:178734014478:ios:1edfc4a9149a1033455c5f',
    messagingSenderId: '178734014478',
    projectId: 'projetofinal-10227',
    storageBucket: 'projetofinal-10227.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVUbpvQXrB8tqBw2hDvgdHJ5h00x6FPWk',
    appId: '1:178734014478:web:48bee91f57792cd1455c5f',
    messagingSenderId: '178734014478',
    projectId: 'projetofinal-10227',
    authDomain: 'projetofinal-10227.firebaseapp.com',
    storageBucket: 'projetofinal-10227.appspot.com',
    measurementId: 'G-P508YVXJ22',
  );
}
